### ISSUE TITLE
Admin GUI

### ISSUE THREAD

**Issue by RvdHout** [kimboslice99/IIS-CGeoIPModule#1]
First of all congratulations and nice job...I was able to build this project without issues, can't make it work with Debug build though, I get HTTP response 503 Service Unavailable, any special instructions needed? 

Thinking about what you said about the fancy IIS Administrator GUI missing, can't you simply write that as additional DLL in C#, eg: CGeoIPModuleGUI.dll? You should be able to take required/needed parts from the https://github.com/RvdHout/IIS-GeoIP2block-Module github repository

You could even write a nice module installer that handles schema and GAC deployment (for GUI DLL), example: http://blog.jdhardy.ca/2008/10/installing-iis7-ui-extensions-with-wix.html

**Comment by kimboslice99** [comment]
Greatly appreciate your input. 503 with debug build might be caused by this

https://github.com/kimboslice99/IIS-CGeoIPModule/blob/06ed3730374a703a4af070ab04f18cab90b349a1/src/Functions.cpp#L452

create the folder and give IIS permission, 503 should stop. I will try to improve this in the future

An installer would be cool, definitely something I will do when I can find more time.

**Comment by kimboslice99** [comment]
Done and done! 😁

**Comment by RvdHout** [comment]
Hi @kimboslice99 

I downloaded the installer the other day (but hadn't time to install it yet), today i saw you updated the installer and downloaded it again, just now I noticed it went from 352 KB to 4.58 MB, that is a huge increase, is this correct?

**Comment by RvdHout** [comment]
Question, how exactly to add Ipv6 address range with prefix to exception rule? The IIS GUI crashes trying to do so

**Comment by RvdHout** [comment]
FYI, loading the project in VS2022 gives all kind of issues/errors within CGeoIPModule.vcxproj

**Comment by kimboslice99** [comment]
The reason for the jump in dll size is the use of PanelSwWixExtension for its XmlSearch method. This is how the installer checks for the location of the `<globalModules>` and `<modules>` elements as they may be found under different paths on different platforms.

Just fixed the IPv6 exception rule issue, seems I forgot to tend to this.

I am not seeing any errors from CGeoIPModule.vcxproj, but I did just make some updates to it so perhaps this resolves it

**Comment by RvdHout** [comment]
Now i get this with a 64-bit release build (installer)

![image](https://github.com/user-attachments/assets/a7648e7a-d302-43db-9b02-3252f2cabfd4)

> The reason for the jump in dll size is the use of PanelSwWixExtension for its XmlSearch method. This is how the installer checks for the location of the `<globalModules>` and `<modules>` elements as they may be found under different paths on different platforms.

This is always 'C:\Windows\System32\inetsrv\config', to my knowledge....i see you made it conditional now, but it seems you have overdone it

**Comment by kimboslice99** [comment]
I actually took a lot of hints from the Modsecurity installer in regards to those paths.

I will probably just change from XmlConfig to a custom action using appcmd to dodge this issue with node paths.

Will update soon to address these things, I do appreciate your time looking at things though!

**Comment by RvdHout** [comment]
You did not have any problems with latest code/installer?

I needed to build my own as i previously (with a private build of my old module) utilized a additional return value, eg; 410 Gone which i like to retain

FYI,  the Actions in GUI do not entirely match the return values / response codes defined in the module it self, eg: Close vs Abort. Reset and Teapot are left out on purpose i guess?

**Comment by kimboslice99** [comment]
I tested on both Win 10 pro and Server 2022.

I will be adding more actions to the GUI as well as the module, I kind of rushed this as I havent had a lot of free time, but I will spend a good amount of time with it over the holidays so you can expect things to get smoothed out shortly

**Comment by RvdHout** [comment]
FYI: Here is another module that also utilizes wix (for hints) 
https://github.com/dionach/StripHeaders

**Comment by RvdHout** [comment]
![image](https://github.com/user-attachments/assets/4ec0e009-9c13-4641-83bb-137e67e67a0a)

This is with latest release, eg: CGeoIPModuleInstallerx64.msi (on Windows Server 2022)
`SHA-256: 40FCAD1340ED999348B32DD32E1DBF907B067C6F41CE7FCD974240401CF4A9E4`

**Comment by RvdHout** [comment]
I managed to install it now, i had to manually delete all file and config references from a previous install, it seems a previous uninstall didn't complete and/of not all is deleted on uninstall
